### ISSUE TITLE
Avoid force-unwrapped optionals

### ISSUE THREAD

**Issue by ayoy** [chalup/advent-swift#1]
Apologies if that's stating the obvious, and it probably is, but you asked for it :)

https://github.com/chalup/advent-swift/blob/c1bae58daca34736f7bc68fc2059eae9cf195906/Sources/advent2019/day1.swift#L20

The alternative that wouldn't crash when given rubbish input is to use `compactMap` that takes a closure returning an optional, and filters nil values:

    return input.compactMap { Int($0) }

**Comment by chalup** [comment]
OK, but in this case I'm parsing the input from file, so crashing is probably preferable to silently dropping the problematic input lines. What would be the idiomatic way of handling such scenario?

**Comment by ayoy** [comment]
In that case you could use `guard` statement:

    return input.map { stringValue in
        guard let intValue = Int(stringValue) else {
            fatalError("oh well")
        }
        return intValue
    }

Note that `$0`-notation is generally discouraged for closures longer than 1 line.
