### ISSUE TITLE
People normally use enum or struct for Error

### ISSUE THREAD

**Issue by ayoy** [chalup/advent-swift#2]
https://github.com/chalup/advent-swift/blob/c1bae58daca34736f7bc68fc2059eae9cf195906/Sources/advent2019/day2.swift#L48

Class is fine (i.e. it compiles), but remember that classes in Swift are reference types, while structs and enums are value types.

**Comment by chalup** [comment]
Ok, why exactly would I want my error to be a value type instead of reference type? (I know the difference between these two; I just don't see the all cons & pros here).

**Comment by ayoy** [comment]
There's a host of reasons, and it might depend on your particular use case, but for me it's that structs are simpler to handle by the runtime. Reference types seem heavier as they need to be handled by the reference counting mechanism.

That said, errors in Swift are in most cases enum types, and you would like to follow the convention. Unless you're interested in inheritance or preventing copying.
